language: node_js

node_js:
  - "0.8"
  - "0.9"
  - "0.10"
  - "0.11"

install:
  - sudo apt-get install cmake
  - npm install

script:
  - npm run-script pretest
  - npm run-script test-verbose

notifications:
  email:
    on_success: change
    on_failure: always
