sudo: false

language: node_js

node_js:
  - 4
  - 6
  - 8

before_script:
  - npm run pretest

script:
  - npm run test-verbose

notifications:
  email:
    on_success: change
    on_failure: always
